### ISSUE TITLE
Doesn't zero password memory when terminal reset fails

### ISSUE THREAD

**Issue by tov** [conradkleinespel/rpassword#41]
In particular, see the error path [here](https://github.com/conradkleinespel/rpassword/blob/master/src/lib.rs#L120), which bails out before zeroing. I’m about to submit a PR that fixes this in a principled and robust (I think!) way.

**Comment by conradkleinespel** [comment]
Hi @tov ! Thanks for reporting this. I've just reviewed #42, once you've had a look at my question I think we can merge this. Cheers!
