### ISSUE TITLE
println!() does not work after rpassword::read_password_from_tty()

### ISSUE THREAD

**Issue by Fishrock123** [conradkleinespel/rpassword#45]
I'm not really sure why this is, but my guess is that the character hiding thing isn't going away?

Also, related, calling this appears to clear any existing text outputted to a tty via `println!()`...

**Comment by conradkleinespel** [comment]
@Fishrock123 What platform (Windows, Linux, OSX, etc) are you testing on ? On UNIX, it should work properly given that [we reset the terminal](https://github.com/conradkleinespel/rpassword/blob/master/src/lib.rs#L122).

Either way, please provide a code example that reproduces the bug you are referring to, that will help with debugging.

**Comment by Fishrock123** [comment]
Ok I think this was my fault somehow, sorry for the false report.

**Comment by conradkleinespel** [comment]
@Fishrock123 No worries, thanks for closing. Feel free to open the issue back up again if you experience any more issues.
