### ISSUE TITLE
Make serde dependency optional?

### ISSUE THREAD

**Issue by BlackHoleFox** [conradkleinespel/rpassword#68]
Heyo,

I was looking at an update to this crate and saw it started bringing in `serde`, `serde_json`, and all their deps. At a glance it doesn't seem used, but just part of a vendored crate.

Would you consider either deleting the `safe_string_serde` module from this crate or a PR that makes it an optional thing so downstream users can use `--no-default-features` to dodge the extra deps?

**Comment by conradkleinespel** [comment]
@BlackHoleFox I'm happy to review a PR to do that, it seems like a good thing to do.

I maintain `rpassword` within this [monorepo](https://github.com/conradkleinespel/duck), which is how the dependency got pulled in by accident. If you can make the PR there, that makes it easier for me.

If you prefer to make a PR here on `rpassword` which may be easier for you as the monorepo is poorly documented, you can do that too. In that case, I will review, close and apply your PR on the monorepo, you will be credited just the same as if I merged here.

Let me know what works for you.

**Comment by BlackHoleFox** [comment]
Delayed here but I can attempt to put something up on your monorepo this weekend and see how it goes :)

**Comment by BlackHoleFox** [comment]
First stab, which is probably busted to start: https://github.com/conradkleinespel/duck/pull/32/. Had a hard time figuring out any _good_ options since the monorepo doesn't use cargo features.

**Comment by sehraf** [comment]
I second this! 
A crate which sole task is to read password, should not depend on a serialization framework.

**Comment by conradkleinespel** [comment]
It turns out `serde` is used by my other project `rooster` which uses `rpassword` so instead of removing serde entirely, I will make the dependency optional with a feature.

**Comment by conradkleinespel** [comment]
I've published v7.0.0 with this change 👍
