### ISSUE TITLE
Support ^U

### ISSUE THREAD

**Issue by tobiasvl** [conradkleinespel/rpassword#70]
If I make a typo in my password and press <kbd>Ctrl</kbd>+<kbd>U</kbd>, it would be nice if it erased my entire password (like in a regular readline session).

It seems like <kbd>Ctrl</kbd>+<kbd>H</kbd> (backspace) is supported already, but when typing my password "blindly" I often don't realize where the typo is, so it's simpler to start over.

**Comment by conradkleinespel** [comment]
Good catch! :+1: If anyone if willing to make a PR for that I'll review it.
