### ISSUE TITLE
Setting rust-version in Cargo.toml

### ISSUE THREAD

**Issue by konstin** [conradkleinespel/rpassword#73]
Would it be possible to set the [rust-version](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) field in Cargo.toml? We would like to support rust 1.59 and therefore currently have to [pin rpassword ^6](https://github.com/PyO3/maturin/pull/1071/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R14-R74), with the rust-version we go switch to rpassword ^6 || ^7

**Comment by messense** [comment]
The 7.0.0 release notes says `You will need at least Rust 1.59 to use this new release.`, but it's not true, The new `dep:xxx` syntax for Cargo features are [stabilized in Rust 1.60.0](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features).

**Comment by conradkleinespel** [comment]
@messense Oh alright, I'll go ahead and change the description of the release then. Thanks for the hint!

**Comment by conradkleinespel** [comment]
@konstin I didn't know there was a field for that. That's good to know! It would make sense to use it, yes :+1:

**Comment by conradkleinespel** [comment]
@konstin I don't have much time to work on `rpassword` at the moment but when I get a chance, I'll add a `rust-version` field. Either way, when it's done I'll make sure to update this issue so you're aware of the change.

**Comment by conradkleinespel** [comment]
Fixed with help from @LSchallot and published in v7.1.0 on crates.io
