### ISSUE TITLE
Ask for retyping the password to catch typos

### ISSUE THREAD

**Issue by ibotty** [conradkleinespel/rpassword#75]
It would be great to have a simple function that prompts for the password, then prompts for the password again and if they match, return.

**Comment by conradkleinespel** [comment]
Hello @ibotty , thanks for the suggestion. But this is outside the scope of what I want to support. The crate is meant to abstract the complexity of cross platform password reading / prompting and that's it.

**Comment by ibotty** [comment]
Well, I'd said that that's exactly a slightly different way of prompting for a password.  In a way `prompt` to `read` is as easy.  I don't want to argue though.  This being outside scope is OK.

**Comment by conradkleinespel** [comment]
Emphasis on the cross platform part. Also because I don't think it's easy to anticipate every way people want to prompt. So I'd rather let people implement that on their end.
