### ISSUE TITLE
Unable to build master branch: error `rtoolbox`

### ISSUE THREAD

**Issue by mrghosti3** [conradkleinespel/rpassword#81]
Cargo build output:
```bash
$ cargo build
error: failed to get `rtoolbox` as a dependency of package `rpassword v7.2.0 (/ddisk/projects/rpassword)`

Caused by:
  failed to load source for dependency `rtoolbox`

Caused by:
  Unable to update /ddisk/projects/rtoolbox

Caused by:
  failed to read `/ddisk/projects/rtoolbox/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Cause:
https://github.com/conradkleinespel/rpassword/blob/1af683038cd34cd9ffafe614af21f77ff6544e0e/Cargo.toml#L22

Also to note, I couldn't find any repo for the crate, only [entry in crates.io](https://crates.io/crates/rtoolbox). Could their be a posibility to replace them with just the packages that are re-exported inside the crate?

**Comment by conradkleinespel** [comment]
Hello there, I develop `rpassword` from here: https://github.com/conradkleinespel/duck/tree/master/projects/rpassword.  may want to clone that repository and build from there.

Let me know how it works out.

**Comment by mrghosti3** [comment]
Yeah, now it works.

Though this a bit confusing when just cloning this standalone repo after reaching it from crates.io .

**Comment by conradkleinespel** [comment]
Totally get it, sorry for the confusion. I mostly maintain this on my own nowadays, after initial contributions from other people, so I just try to make it easy for me to keep alive.

**Comment by mrghosti3** [comment]
Fair enough. Thank you for your work. I would suggest you to link the crates.io pages with monorepo. Great example would be `ed25519` crate.

**Comment by conradkleinespel** [comment]
Good idea! Making a note of it, I've got a couple things I need to update. Thanks for the suggestion! :+1:
