### ISSUE TITLE
Expose HiddenInput in the public interface?

### ISSUE THREAD

**Issue by ifd3f** [conradkleinespel/rpassword#96]
Would it be possible to expose the HiddenInput struct in the public interface of the crate? I have a somewhat complicated usecase and I would like to use it directly.

**Comment by conradkleinespel** [comment]
Hello @ifd3f, no sorry, that's not the point of this library, but feel free to copy/paste de code provided you keep the licensing information in there (Apache 2 license + copyright notice). It's only a couple of dozen lines of code after all :wink:
